# Este flujo de trabajo de GitHub Actions automatiza el proceso de despliegue del proyecto.
# 
# Nombre del Workflow: Deploy
#
# Triggers:
#   - Se ejecuta en cada push al repositorio.
#
# Jobs:
#   1. build:
#      - Se ejecuta en la última versión de Ubuntu.
#      - Pasos:
#        - Imprime una variable secreta para propósitos de depuración.
#        - Realiza checkout del código del repositorio.
#        - Configura Node.js versión 18.
#        - Instala las dependencias del proyecto usando npm.
#        - Ejecuta las pruebas con npm.
#        - Construye el proyecto usando el script de build de npm.
#        - Sube los artefactos de build desde el directorio 'public/' para el despliegue.
#
#   2. deploy:
#      - Se ejecuta en la última versión de Ubuntu.
#      - Depende de la finalización exitosa del trabajo 'build'.
#      - Establece permisos para el despliegue en GitHub Pages y token OIDC.
#      - Especifica el ambiente de despliegue como 'github-pages'.
#      - Despliega los artefactos subidos a GitHub Pages usando la acción deploy-pages.
#      - Expone la URL de la página desplegada como salida.

name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo "${{ secrets.TOKEN_SECRETS }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build page
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
            path: public/
  deploy:
    runs-on: ubuntu-Latest
    needs: build

    permissions:
        pages: write
        id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4